### PR TITLE
added preprocessing script

### PR DESCRIPTION
**Pull request by ZER-0-NE**
I've added a pre-processing script which:

- resamples and pads all the files to be of same length
- allows normalization of data
- allows to compute mel-scaled feature spectrogram
- allows computation of Per-Channel Energy Normalization (PCEN)
- allows computation of Wavelet Denoising

By using argaprse, we can run the script via CLI allowing us to have a choice over factors like:

- choosing directory with files to run on (required)
- sampling rate
- audio duration
- apply mfcc along with choosing number of mfcc's to return

The data files are iterated over and a new folder is made (if not already present) in the same directory with the name "PreProcessed" where the images are stored.

The images before saving are displayed and I've tried to fast it up using [this](https://bastibe.de/2013-05-30-speeding-up-matplotlib.html) article which @yosoyjay mentioned. The `fig.canvas.update()` line has a bug (or perhaps it works on a different backend), which can be rectified later.

The images have been saved with [high-quality factor of 95](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.savefig.html) in png format. The dpi can be adjusted over along with dimensions of the image.

As a sample, showing the pre-processed images below:

1) Spectrogram with Wavelet Denoising and PCEN:
spec_denoised1

The above image has some noise on the left which has been intensified after applying wavelet denoising. It may perhaps be due to the implementation difference between librosa and scikit image.

2) Spectrogram without Wavelet Denoising and PCEN:
spec_PCEN1

This image has rather less noise and the whale calls are also quite visible. This method can be a good candidate for futher steps as it is important that images are clear and visible to be given as input to the CNN architecture. We can discuss this.

I am currently trying to make the noise less in 1) and 2) by balancing between the n_fft and window size  as I've found it [essential](https://dsp.stackexchange.com/questions/248/how-do-i-optimize-the-window-lengths-in-stft) to make the whale calls more clear on the images

### CODE REVIEW

**Comment by yosoyjay** [comment]
@ZER-0-NE Looks basically how I envisioned it would work.  Thanks for the simple comments in the main that provide a good overview of what's going on in the script.

A couple of notes to tighten this up:
- Let's get in good habits and apply flake8 to all code that's checked in.  I'm definitely in favor of skipping line-lengths (E501), but we should agree on which one's we will ignore.  I ran `flake8 PreProcessing/preprocessing.py` to check it.
- What's going on with `def preprocessing_fx(x): return`?
- I think we can pull the license out of the file and put it in a file in the top-level of the project

**Comment by yosoyjay** [comment]
The project should also have a requirements.txt or environment.yml (or, both) so people can create environments to run the code.  Creating those files starting with the requirements for this script would be a good start.

**Comment by ZER-0-NE** [comment]
@yosoyjay 

> * Let's get in good habits and apply flake8 to all code that's checked in.  I'm definitely in favor of skipping line-lengths (E501), but we should agree on which one's we will ignore.  I ran `flake8 PreProcessing/preprocessing.py` to check it.

I previously checked with `pycodestyle preprocessing.py`, both give almost the same errors and warnings. Apart from (E501), we are getting the (F841) warning of not using assigned variables. This comes from the `wavelet_denoising` method. I've used `BayesShrink` method for now as it worked out well for our data. I've kept the other `VisuShrink` method as an option, so I think we can ignore the warning.



> * What's going on with `def preprocessing_fx(x): return`?

It kind of works like an identity function and what I've found other users were using for their data. I use `preprocessing_fn = lambda x: x` earlier but following pep8 standards I was asked to use `def` instead of `lambda`. We can remove the identity function overall, if we want.

> * I think we can pull the license out of the file and put it in a file in the top-level of the project

Yeah. I think the license exists in the top-level of directory. I'll remove from here.

> The project should also have a requirements.txt or environment.yml (or, both) so people can create environments to run the code. Creating those files starting with the requirements for this script would be a good start.

Yes. I'll make the requirements.txt file now. I haven't used (or created) environment.yml much (maybe once), so I might need some help with that.

**Comment by yosoyjay** [comment]
> > * What's going on with `def preprocessing_fx(x): return`?
> 
> It kind of works like an identity function and what I've found other users were using for their data. I use `preprocessing_fn = lambda x: x` earlier but following pep8 standards I was asked to use `def` instead of `lambda`. We can remove the identity function overall, if we want.

Yeah, flake8 will complain about naming an anonymous (lambda) function, but sometimes it just what folks do.  I'm totally cool with use of the named lambda if it's a community standard.

> Yes. I'll make the requirements.txt file now. I haven't used (or created) environment.yml much (maybe once), so I might need some help with that.

Yeah, no problem.  The environment.yml is useful for folks who tend to use conda and not virtualenvs.

**Comment by ZER-0-NE** [comment]
#8 partially done. I am looking forward to using it on the actual data that is still getting uploaded.

**Pull request merged**
