### PR TITLE
added orcacnn webapp with docker support.  Closes #4

### LINKED ISSUE #4: Develop summarizer
The primary job of this tool is to detect orca in passive acoustic datasets comprised of a pipeline consisting of stages to: 1) preprocess and standardize input data, 2) apply a model to identify the presence of orca within the dataset, 3) apply additional models to extract additional information about the orca call including signal type and pod, and 4) create a summary of the results of the pipeline indicating presence of orca along with time and any additional information.

The issue here is to develop a tool that summarizes what was learned in #3 to create stage 4 of the pipeline.  The output should encapsulate all of the information extracted from the pipeline and output in formats amenable for humans (html?) and apis (json?).

### PR DESCRIPTION
**Pull request by ZER-0-NE**
#### 1. Directory structure:

**Earlier**
```
-- Detection                   
-- Pod-Classification
-- PreProcessing    
-- README.md        
-- assets    
-- requirements.txt
```

**Now**

```
-- app
-- Pod-Classification
-- README.md
-- assets
-- docker-compose.yml
-- nginx
-- run.sh

```

 #### 2. Minor code changes:

 - Introduced `**kwargs` in pre-processing scripts to help take inputs directly from flask scripts.
 - `from tensorflow.keras.models import load_model` in `Detection.predict`

### What's new:

To aid #4, a very simple `flask` web app has been added with support for:

- Pre-processing acoustic data (`.wav` files, for now)
- Displaying all pre-processed spectrograms and then allowing for prediction using the `predict` prompt button
- 4 ML models to help in prediction
- uWSGI web server
- Nginx as a reverse proxy in front of uWSGI
- Two docker containers for uWSGI app and nginx
- Uses [BuildKIt](https://docs.docker.com/develop/develop-images/build_enhancements/) to build images

The look of web app:

Screenshot from 2021-04-28 12-12-41

Screenshot from 2021-04-28 12-14-27

Screenshot from 2021-04-28 12-14-45

This is a starting point of how the `orcacnnapp` should function and look. I believe there are a lot of functionalities as well as UI changes that can be made. This is more of a learning experience for me since I'm beginning to dive deep into MLOps.

Below are a few future tasks I can think of at the top of my head:

- Display wave of acoustic data (something close to [OrcaAL](https://orcasound.github.io/orcaal/listen)) on the homepage.
- After predicting, display start and end times of detected calls, preferably in a `.csv` file
- Averaging the predictions from the 4 models to better validate orca calls and find start and end times (Ensemble model?)
- Maybe add test support? (I'm planning to learn and add more [MLOps tooling](https://www.reddit.com/r/MachineLearning/comments/mfca0p/d_whats_the_simplest_most_lightweight_but/))

@yosoyjay If you could provide some feedback or suggestions for the code and perhaps UI too, I'd very much appreciate it. Being a novice in docker/deployment, I'd like to know what you would've done differently or anything?

### CODE REVIEW

**Comment by ZER-0-NE** [comment]
I'll be adding documentation soon regarding the web app + docker + uWSGI + Nginx and how they interact.

**Comment by yosoyjay** [comment]
I'm excited to see a webapp!  Generally, I think you are on the right track, but I ran into trouble uploading a file to the app.  Here are my two attempts of trying to upload a .wav file.

1. If I click "Choose File", select a file, then press upload, I get 500.

```
app      | ERROR:orcacnnapp:Exception on /home [POST]
app      | Traceback (most recent call last):
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
app      |     response = self.full_dispatch_request()
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
app      |     rv = self.handle_user_exception(e)
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
app      |     rv = self.dispatch_request()
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
app      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
app      |   File "/app/./orcacnnapp/main/routes.py", line 27, in get_input_image
app      |     uploaded_file.save(os.path.join(
app      |   File "/usr/local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3013, in save
app      |     dst = open(dst, "wb")
app      | FileNotFoundError: [Errno 2] No such file or directory: 'uploads/00.wav'
```

2. If I drag a file and hit upload, I get 400 and the logs show:
```
app      | ERROR:orcacnnapp:Exception on /home [POST]
app      | Traceback (most recent call last):
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
app      |     response = self.full_dispatch_request()
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
app      |     rv = self.handle_user_exception(e)
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
app      |     rv = self.dispatch_request()
app      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
app      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
app      |   File "/app/./orcacnnapp/main/routes.py", line 27, in get_input_image
app      |     uploaded_file.save(os.path.join(
app      |   File "/usr/local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3013, in save
app      |     dst = open(dst, "wb")
app      | FileNotFoundError: [Errno 2] No such file or directory: 'uploads/00.wav'
``` 

It seems as though the directory `uploads` does not exist.

Another thing to be mindful of is that the port specified for the app (660) is in the 0-1023 range which is reserved for specific services by convention.

**Comment by ZER-0-NE** [comment]
Hey @yosoyjay . Hope you are safe and well!
I'm glad to see we both are working on the OrcaCNNapp.

I should've been more careful about that folder. The `uploads` folder saves the user-uploaded file temporarily and the files inside are deleted as soon as the spectrograms are created.

The folder is empty initially and so went untracked by git when I first created the PR. If you create a folder inside the `app/` directory, you should see everything working fine.

I'll be adding a commit to fix this. Thanks! And good catch on that port number.

**Comment by yosoyjay** [comment]
Okay, looks like that issue was fixed and the classifier works -- nice!

Is the goal to use the `run.sh` script to actually run the app?  If not, the name isn't quite accurate because it removes a running instance and then builds a new one. Right now running `run.sh`, you need to use `docker-compose up` to get the app running so it's not quite automated now.

**Comment by ZER-0-NE** [comment]
> Is the goal to use the `run.sh` script to actually run the app? If not, the name isn't quite accurate because it removes a running instance and then builds a new one. Right now running `run.sh`, you need to use `docker-compose up` to get the app running so it's not quite automated now.

You're right in pointing that out. I was running everything manually on my machine for quite some time I didn't realize to put that up.
Apart from that, what do you think would be a good addition to the app? UI/feature-wise? Or any other suggestion?

**Comment by yosoyjay** [comment]
I forgot to mention, it's generally not a good idea to put `sudo` in scripts.  Rather, if required, you can use it when calling the script.  So, just remove `sudo` in `run.sh` and I think it's good to go.

**Comment by ZER-0-NE** [comment]
Sounds good! I'll make the changes and merge with the next commit.

**Pull request merged**
